config/routes.rb
Rails.application.routes.draw do
  resources :participations
  root to: "events#index"
  get 'home/index'
  get 'home/secret'
  devise_for :users
  resources :events
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_many :attendances
  validates :start_date, :presence => true
  validates :duration, :presence => true, :numericality => { greater_than: 0 }
  validates :title, :presence => true, :length => { in: 5..140 }
  validates :description, :presence => true, :length => { in: 20..1000 }
  validates :price, :presence => true, :numericality => { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, :presence => true
  validate :date_before
  validate :multiple_of_5

  def date_before
    if start_date < DateTime.now
      errors.add(:start_date, "can't be in to the past")
    else
      return true
    end
  end

  def multiple_of_5
    if duration % 5 != 0
      errors.add(:duration, "it should be a multiple of 5")
    else
      return true
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances # ffffff
  has_many :events

  validates :password, :presence => true,
    :confirmation => true,
    :length => {:within => 6..40},
    :on => :create
  validates :password, :confirmation => true,
    :length => {:within => 6..40},
    :allow_blank => true,
    :on => :update

  def welcome_send

    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_paramaters, if: :devise_controller?

  def configure_devise_paramaters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :first_name, :last_name, :description, :password, :password_confirmation) }
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
        @event = Event.find(params[:format])
    end

    def show
        
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create(
            :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @event = Event.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @event = Event.find(params[:id])
  end

  def new
    # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end
  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    @event = Event.create!(title: params["title"], description: params["description"], price: params["price"], location: params["location"], duration: params["duration"], start_date: params["start_date"], admin_id: current_user.id)
    redirect_to event_path(@event.id)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @participation, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.fetch(:participation, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%= @event.price %>€ a payer</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @event.price %>00"
          data-locale="auto"></script>
<% end %>

app/views/events/index.html.erb
<h1 class="text-center m-4 mb-5">Bienvenue à toi visiteur</h1>
<div class="row col-10 m-auto">
    <% @event.each do |event| %>
        <div class="col-sm-6 mb-5">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= event.title %></h5>
                    <p class="card-text">Cette event a ete cree par: <%= User.find(event.admin_id).email %>.</p>
                    <p class="card-text">prix: <%= event.price %>.</p>
                    <a href="<%= event_path(event.id) %>" class="btn btn-primary">Voir l'event</a>
                </div>
            </div>
        </div>
    <% end %>
    <% if user_signed_in? %>
        <a href="<%= new_event_path %>" class="btn btn-primary">cree un event</a>
    <%else%>
        <a href="<%= new_user_session_path %>" class="btn btn-primary">cree une event</a>
    <% end %>
</div>

app/views/events/new.html.erb
<h1 class="text-center">cree un event</h1>
<div class="col-6 m-auto">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
        <div class="form-group">
            <%= label_tag "titre de l'event" %>
            <%= text_field_tag 'title', @title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag "description de l'event" %>
            <%= text_area_tag 'description', @description, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag "lieux de l'event" %>
            <%= text_field_tag 'location', @location, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag "date de debut" %>
            <%= datetime_field_tag 'start_date', @start_date, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag "duree de l'event (en minutes, multiple de 5)" %>
            <%= number_field_tag 'duration', @duration, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label_tag "prix de l'event" %>
            <%= number_field_tag 'price', @price, class: "form-control" %>
        </div>
        <input type="submit" class="btn btn-primary" value="Crée cette event!">
    <% end %>
</div>

app/views/events/show.html.erb
<h1 class="text-center m-4 mb-5">Voici les details de cette evenement!</h1>
<%# <div class="row col-10 m-auto">   %>
    <div class="text-center m-5">
        <h2><%= @event.title %></h2>
                <h2></h2>
        <p>description de l'evenement: <%= @event.description %></p>
        <p>cette event aura lieux le: <%= @event.start_date %></p>
        <p>la date de fin de cette event: <%= @event.start_date + @event.duration * 60 %></p>
        <p>cette event aura lieux dans cette ville: <%= @event.location %></p>
        <p>Participer a cette event coute : <%= @event.price %>euro!</p>
        <p>event cree par: <%= User.find(@event.admin_id).email %></p>
        <% a = current_user %>
        <% b = User.find(@event.admin_id) %>
        <% if b.id != a.id %> <%= link_to "Participer", new_charge_path(@event.id) , :class => "btn btn-primary" %>
 
         <% end %>


    </div>
<%# </div> %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<%-# Header  de mon programme qui contient la nav et le footer-%>

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <title>Eventbrite</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Accueil<span class="sr-only">(current)</span></a>
            </li>
            <%# <li class="nav-item">
              <a class="nav-link" href="/team">Team</a>
            </li> %>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Secret page", home_secret_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Edit email / password", edit_user_registration_path, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">    
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="p-4">
      <p class="text-center">Made with ♥ by moussaillons</p>
    </footer>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/participations/_form.html.erb
<%= form_with(model: participation, local: true) do |form| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
      <% participation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation', new_participation_path %>

app/views/participations/new.html.erb
<h1>New Participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Back', participations_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>